connect sftp://Allermetrix01:All3rm3tr1x#@44.235.72.333/OrdersOutbound/
cd /OrdersOutbound/
lcd C:\\apps\\Orders\\SanJuan
mget --exists s ^allermetrixorders.txt
dir
lcd C:\\apps\\Orders\\SanJuan\\BackupOrders
mget --exists s ^allermetrixorders.txt 
mdel ^a
dir
disconnect
connect sftp://amx:xD1GkuK7a7DK8!@amxemr.com/home/amx/HL7/500258/Orders
cd /home/amx/HL7/500258/Orders/
lcd C:\\apps\\Orders\\SanJuan
mput --exists o ^allermetrixorders.txt 
ldir ^a
lmdel ^a
ldir
disconnect
quit