  MODULE('ALIS8072.CLW')
Main                   PROCEDURE                      !Wizard Application for C:\C6\ALIS2\Alis8\am8.dct
BrowseBilling          PROCEDURE                      !Browse the Billing file
BrowseNameList         PROCEDURE                      !Browse the NameList file
SelectBilling          PROCEDURE                      !Select a Billing Record
UpdateNameList         PROCEDURE                      !Form NameList
AssessionLookup        PROCEDURE                      !Browse the Patient file
autoNumb               PROCEDURE                      !Form Billing
UpdatePayment          PROCEDURE                      !Form Payments
UpdateBilling          PROCEDURE                      !Form Billing
  END
