  MODULE('ALIS8079.CLW')
CovidRequestForm       PROCEDURE
ImportCovidTests       PROCEDURE
GetOrderCPL            PROCEDURE                      !Window
ExportResult           PROCEDURE                      !Window
getHL7Orders           PROCEDURE
ProcessOrdersHL7       PROCEDURE
UploadHL7              PROCEDURE
GetOrders              PROCEDURE                      !Window
ExportPortal           PROCEDURE                      !Window
ExportUpdates          PROCEDURE(LONG,LONG)
  END
