  MODULE('ALIS8078.CLW')
FindInsurance          PROCEDURE
ListPhysicians         PROCEDURE
UploadInsurance        PROCEDURE
DiagCodesLookup        PROCEDURE                      !Browse the DiagnosticCodes file
UpdateDiagnosticCodes  PROCEDURE                      !Form DiagnosticCodes
ReadPDF                PROCEDURE
RequestForm            PROCEDURE                      !Browse the RequestForms file
UpdateRequestForms     PROCEDURE                      !Form RequestForms
virus                  PROCEDURE                      !Browse the Test file
ExportCovid            PROCEDURE
  END
