  MODULE('ALIS8074.CLW')
amxUpdateDiet          PROCEDURE(LONG)                !Window
GetLetters             PROCEDURE                      !Process the Billing File
BillingFees            PROCEDURE
BillingCheck           PROCEDURE                      !Browse the Patient file
AddName                PROCEDURE
Billing                PROCEDURE                      !Browse the Billing file
Billing2               PROCEDURE                      !Browse the Billing file
Export2BillingQB       PROCEDURE
BatchLetters           PROCEDURE
AddBillingItems        PROCEDURE
  END
